# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2d8a6806879259dddcefec62303a46e6bb24daae9ff343634328f87b9d49c830a34d89bb232a31d13d1e839590b9ee2d12f38360ba97134256a09bfdf65c934

test:
  secret_key_base: a77e753547780e9ce40824607e1f069b61b31b24b759293820e4fcc630467264d66ee89cbda3ee9c675f6f429577410d2e582e47b445e0c7d576af7f65715c4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
